# AWS CodeBuild CI Configuration
version: 0.2

phases:
  pre_build:
    commands:
      - git status
      - git log
      - lein test

  build:
    commands:
      - npx webpack -p
      - lein uberjar

  post_build:
    commands:
      - docker build -t whiplash:test .
      - docker push 296027954811.dkr.ecr.us-west-2.amazonaws.com/whiplash:test

