apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
## This used to work but now breaks the website, so it is commented out
#  tls:
#    - hosts:
#        - whiplashesports.com
  rules:
    - host: whiplashesports.com
      http:
        paths:
          - path: /
            backend:
              serviceName: whiplash-service
              servicePort: 3000
