apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiplash-web
  labels:
    app: whiplash
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # Make same as total replicas. We do this because a server running the previous version may be routed
      # a request for a js bundle that it does not have. The website will fail to load properly for the user
      # in this case.
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: whiplash
  template:
    metadata:
      labels:
        app: whiplash
    spec:
      #serviceAccountName: datomic-s3
      containers:
        - name: whiplash
          image: 296027954811.dkr.ecr.us-west-2.amazonaws.com/whiplash:0.1.155
          imagePullPolicy: IfNotPresent
          ports:
            - name: container-port
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /v1/healthz
              port: container-port
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/healthz
              port: container-port
            initialDelaySeconds: 15
            periodSeconds: 5
